### ISSUE TITLE
Fire Alarm System :Arduino

### ISSUE THREAD

**Issue by Rhythm1810** [NewLeapKjsieit/BeliefSat#25]
Create a circuit for Fire Alarm System which will have necessary Functionalities and code with the help of Arduino

**Comment by varunkanbhat18** [comment]
https://www.tinkercad.com/things/8ppLzMDAwmo-fire-alarm-system-vk/editel?sharecode=dURrn1O2c5jHb1W0II4TmfLgoQTHHQ4GE59YnbGzR6g
